version: '3'

services:

  postgres:
    # Vanilla PostGIS database.
    image: mdillon/postgis:9.6-alpine
    volumes:
      - database:/var/lib/postgresql/data 

  # elasticsearch:
  #   image: elasticsearch:5.6

  rabbitmq:
    # Vanilla RabbitMQ service. This is needed by celery
    image: rabbitmq:3.7
  
  nginx:
    # Nginx is serving django static and media files and proxies to django and geonode
    image: spcgeonode/nginx:latest # TODO : versionize
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - django
      - geoserver
    volumes:
      - static:/spcgeonode-static
      - media:/spcgeonode-media

  django:
    # This is our custom django application. It includes Geonode.
    image: spcgeonode/django:latest # TODO : versionize
    build: ./django/
    env_file:
      - ./django/docker-compose.env
    volumes:
      - static:/spcgeonode-static
      - media:/spcgeonode-media
    depends_on:
      - postgres
    entrypoint: ["/spcgeonode/docker-entrypoint.sh"]
    command: ["uwsgi", "--chdir=/spcgeonode", "--module=spcgeonode.wsgi", "--socket=:8000", "--processes=5"]
    
  celery:
    # This is the celery worker that executes celery tasks created by Django.
    image: spcgeonode/django:latest # TODO : versionize
    env_file:
      - ./django/docker-compose.env
    depends_on:
      - django
    command: 'python manage.py celery worker --app=geonode.celery_app:app -B -E -l INFO'

  celerycam:
    # This is the celery camera that monitors celery tasks and populate the djcelery django admin interface
    image: spcgeonode/django:latest # TODO : versionize
    env_file:
      - ./django/docker-compose.env
    depends_on:
      - django
    command: 'python manage.py celerycam'

  geoserver:
    # This is the geoserver backend required by geonode.
    image: spcgeonode/geoserver:latest # TODO : versionize
    build: ./geoserver/
    env_file:
      - ./geoserver/docker-compose.env
    volumes:
      - geodatadir:/spcgeonode-geodatadir/
    depends_on:
      - postgres

  # backuper:
  #   image: spcgeonode/backuper:latest # TODO : versionize
  #   build: ./backuper/
  #   volumes:
  #     - database:/tobackup/spcgeonode-database
  #     - media:/tobackup/spcgeonode-media
  #     - geodatadir:/tobackup/spcgeonode-geodatadir

volumes:
  static:
  media:
  database:
  geodatadir:
