version: '3'

services:
  django:
    environment:
      - "DEBUG=True"
    volumes:
      - './django:/spcnode'
    command: ["uwsgi", "--chdir=/spcnode", "--module=spcnode.wsgi", "--env=DJANGO_SETTINGS_MODULE=spcnode.settings", "--socket=:8000", "--py-autoreload=2"]
  postgres:
    ports:
      - "5432:5432"
