version: '3.4'


# Common Django template for Geonode, Celery and Celerycam services below
# RANCHER : manually copy this to each service below
x-common-django:
  &default-common-django
  image: olivierdalang/spcgeonode:django-dev
  environment:
    - "DEBUG=True"
  volumes:
    - ./django:/spcgeonode/
    - ./_volume_static:/spcgeonode-static/
    - ./_volume_media:/spcgeonode-media/

services:
  django:
    << : *default-common-django
    command: ["uwsgi", "--chdir=/spcgeonode", "--module=spcgeonode.wsgi", "--env=DJANGO_SETTINGS_MODULE=spcgeonode.settings", "--socket=:8000", "--py-autoreload=2"]
  celery:
    << : *default-common-django
  celerycam:
    << : *default-common-django

  nginx:
    image: olivierdalang/spcgeonode:nginx-dev
    volumes:
      - ./_volume_static:/spcgeonode-static/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_certbot:/spcgeonode-certbot/

  geoserver:
    image: olivierdalang/spcgeonode:geoserver-dev
    volumes:
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  letsencrypt:
    image: olivierdalang/spcgeonode:letsencrypt-dev
    volumes:
      - ./_volume_certbot:/spcgeonode-certbot/

  pgdumper:
    image: olivierdalang/spcgeonode:pgdumper-dev
    build: ./pgdumper/
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/

  syncthing:
    image: olivierdalang/spcgeonode:syncthing-dev
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  rclone:
    image: olivierdalang/spcgeonode:rclone-dev
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  postgres:
    ports:
      - "5432:5432"
