version: '3.4'

# TODO : replace olivierdalang repository by pacificcommunity
secrets:
  admin_username:
    external: true
  admin_password:
    external: true



x-common-django:
  # Common Django template for geonode, celery and celerycam
  &default-common-django
  image: olivierdalang/spcgeonode:django-latest # TODO : versionize
  build: ./django/
  environment: # WARNING changes here must be repercuted to django, celery and celerycam
    - GEOSERVER_PUBLIC_LOCATION=http://${DOMAIN_NAME}/geoserver/
    - ALLOWED_HOSTS=${WAN_HOST},${LAN_HOST},nginx # we need nginx to allow calls to Geonode OAuth API from Geoserver
    - ADMIN_EMAIL=${ADMIN_EMAIL}
  env_file:
    - ./django/docker-compose.env
  volumes:
    - static:/spcgeonode-static
    - media:/spcgeonode-media
  depends_on:
    - postgres
  secrets:
    - admin_username
    - admin_password 
  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure
  networks:
    - default-net
    


services:

  django:
    # This is our custom django application. It includes Geonode.
    << : *default-common-django
    entrypoint: ["/spcgeonode/docker-entrypoint.sh"]
    command: ["uwsgi", "--chdir=/spcgeonode", "--module=spcgeonode.wsgi", "--socket=:8000", "--processes=5"]
    
  celery:
    # This is the celery worker that executes celery tasks created by Django.
    << : *default-common-django
    command: 'python manage.py celery worker --app=geonode.celery_app:app -B -E -l INFO'

  celerycam:
    # This is the celery camera that monitors celery tasks and populate the djcelery django admin interface
    << : *default-common-django
    command: 'python manage.py celerycam'

  postgres:
    # Vanilla PostGIS database.
    image: mdillon/postgis:9.6-alpine
    volumes:
      - database:/var/lib/postgresql/data 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default-net

  # elasticsearch:
  #   image: elasticsearch:5.6

  rabbitmq:
    # Vanilla RabbitMQ service. This is needed by celery
    image: rabbitmq:3.7 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default-net
  
  nginx:
    # Nginx is serving django static and media files and proxies to django and geonode
    image: olivierdalang/spcgeonode:nginx-latest # TODO : versionize
    build: ./nginx/
    environment:
      - WAN_HOST=${WAN_HOST}
      - LAN_HOST=${LAN_HOST}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - geoserver
    volumes:
      - static:/spcgeonode-static
      - media:/spcgeonode-media 
      - certbot-challenge:/spcgeonode-certbot-challenge
      - certbot-keys:/spcgeonode-certbot-keys
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default-net

  geoserver:
    # This is the geoserver backend required by geonode.
    image: olivierdalang/spcgeonode:geoserver-latest # TODO : versionize
    build: ./geoserver/
    env_file:
      - ./geoserver/docker-compose.env
    volumes:
      - geodatadir:/spcgeonode-geodatadir/
    depends_on:
      - postgres 
    secrets:
      - admin_username
      - admin_password 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default-net

  letsencrypt:
    image: olivierdalang/spcgeonode:letsencrypt-latest # TODO : versionize
    build: ./letsencrypt/
    environment:
      - WAN_HOST=${WAN_HOST}
      - LAN_HOST=${LAN_HOST}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    # command: /bin/true
    volumes:
      - certbot-challenge:/spcgeonode-certbot-challenge/
      - certbot-keys:/etc/letsencrypt/
    # volumes:
    #   - letsencrypt_certs:/etc/letsencrypt
    #   - letsencrypt_www:/var/www/letsencrypt
    networks:
      - default-net

  # backuper:
  #   image: olivierdalang/spcgeonode:backuper-latest # TODO : versionize
  #   build: ./backuper/
  #   volumes:
  #     - database:/tobackup/spcgeonode-database
  #     - media:/tobackup/spcgeonode-media
  #     - geodatadir:/tobackup/spcgeonode-geodatadir 
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - default-net

  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   # volumes:
  #   #   - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   networks:
  #     - default-net

volumes:
  static:
  media:
  database:
  geodatadir:
  certbot-challenge:
  certbot-keys:

# For some reason docker-swarm doesn't work when networks arent explicitely set
networks:
   default-net: