version: '3.4'


# Common Django template for Geonode, Celery and Celerycam services below
# RANCHER : manually copy this to each service below
x-common-django:
  &default-common-django
  image: olivierdalang/spcgeonode2.6:django-dev
  environment:
    - "DEBUG=True"
  volumes:
    - .:/spcgeonode/
    - ./_volume_static:/spcgeonode-static/
    - ./_volume_media:/spcgeonode-media/

services:
  django:
    << : *default-common-django
    command: ["uwsgi", "--chdir=/spcgeonode", "--module=spcgeonode.wsgi", "--socket=:8000", "--py-autoreload=2"]
  celery:
    << : *default-common-django
  celerycam:
    << : *default-common-django

  nginx:
    image: olivierdalang/spcgeonode2.6:nginx-dev
    volumes:
      - ./_volume_static:/spcgeonode-static/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_certificates:/spcgeonode-certificates/

  geoserver:
    image: olivierdalang/spcgeonode2.6:geoserver-dev
    volumes:
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  letsencrypt:
    image: olivierdalang/spcgeonode2.6:letsencrypt-dev
    volumes:
      - ./_volume_certificates:/spcgeonode-certificates/

  pgdumper:
    image: olivierdalang/spcgeonode2.6:pgdumper-dev
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/

  rclone:
    image: olivierdalang/spcgeonode2.6:rclone-dev
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  postgres:
    ports:
      - "5432:5432"
