version: '2'
catalog:
  name: "SPC Geonode"
  description: "SPC Geonode"
  version: "0.0.6"
  uuid: spc-geonode-0.0.6
  questions:
    - variable: WAN_HOST
      label: "Hostname for WAN access"
      description: "Enter the domain name you will be using. This will setup SSL certificates and configure Nginx to accept connections on this domain name. Leave this empty if you only plan to use Geonode on LAN."
      required: false
      default: null
      type: "string"
    - variable: LAN_HOST
      label: "Hostname for LAN access"
      description: "Enter the hostname name you will be using (most likely a LAN IP). This will configure Nginx to accept unencrypted connections on this domain name. Leave this empty if you only plan to use Geonode on WAN."
      required: false
      default: null
      type: "string"
    - variable: ADMIN_EMAIL
      label: "Email of the administrator"
      description: "This will be used as contact information for Let's Encrypt certificates and as email for the superuser"
      required: true
      type: "string"
    - variable: _CHECK_ADDED_SECRET_SERVICE
      label: "Reminder : did you add the Rancher Secrets service from the catalog ?"
      description: "For this stack to work, you need to add the Rancher Secrets service from the catalog. See http://rancher.com/docs/rancher/v1.4/en/cattle/secrets/#enabling-secrets-in-containers for more informations."
      required: true
      default: null
      type: "boolean"
    - variable: _CHECK_ADDED_SECRET_ADMIN_USERNAME
      label: "Reminder : did you create the ADMIN_USERNAME secret ?"
      description: "For this stack to work, you need to create an ADMIN_USERNAME secret. This will be the Geonode and Geoserver administrator username"
      required: true
      default: null
      type: "boolean"
    - variable: _CHECK_ADDED_SECRET_ADMIN_PASSWORD
      label: "Reminder : did you create the ADMIN_PASSWORD secret ?"
      description: "For this stack to work, you need to create an ADMIN_PASSWORD secret. This will be the Geonode and Geoserver administrator password"
      required: true
      default: null
      type: "boolean"
services:    
  django:
    scale: 1
    start_on_create: true
  celery:
    scale: 1
    start_on_create: true
  celerycam:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
  # elasticsearch:
  #   scale: 1
  #   start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  geoserver:
    scale: 1
    start_on_create: true
  letsencrypt:
    # TODO : find a way to not restart too quickely on failure, because then we hit letsencrypt limits
    scale: 1
    start_on_create: true
  
